# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaverWebtoon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NaverWebtoon

pod 'Alamofire'
pod 'CryptoSwift'
pod 'SnapKit'

  target 'NaverWebtoonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NaverWebtoonUITests' do
    # Pods for testing
  end

end
